//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagement.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActiveCourse
    {
        public ActiveCourse()
        {
            this.CourseStudents = new HashSet<CourseStudent>();
        }
    
        public int ID { get; set; }
        public int CourseID { get; set; }
        public int TeacherID { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public bool CourseEnded { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Teacher Teacher { get; set; }
        public virtual ICollection<CourseStudent> CourseStudents { get; set; }
    }
}
